### ISSUE TITLE
怎么运行?

### ISSUE THREAD

**Issue by JoeyBling** [fex-team/swiper#27]
怎么运行?

**Comment by zhangbobell** [comment]
你可以参考 Readme 的[基本用法](https://github.com/fex-team/swiper#基本用法)部分，不过由于还没有正式发布 beta 版本，第一步中的 css 和 js 推荐引用我们的预览版地址：

css: //fex.bdstatic.com/h5jscss/3eef8fa1e51b1fb3b1d4afe49d4cfe0e_swiper.min.css
js: //fex.bdstatic.com/h5jscss/e2e06f0f7ce001b431d6c9bd92241ea9_swiper.min.js

另外，可以参考 examples 文件夹里面的例子进行。

**Comment by JoeyBling** [comment]
我是问NPM怎么安装的?
命令没写

**Comment by zhangbobell** [comment]
目前 swiper 还没有正式发布，暂时还没法通过 npm 直接安装，不过你可以通过 `npm install fex-team/swiper` 进行安装。
