### ISSUE TITLE
请问是否支持左右翻页

### ISSUE THREAD

**Issue by pakey** [fex-team/swiper#29]
如题？
另外可否告知在百度的线上应用

**Comment by pakey** [comment]
isVertical  原来已经有了

**Comment by zhangbobell** [comment]
使用 `isVertical: false` 即是左右翻页，详见 README 的[配置选项](https://github.com/fex-team/swiper#%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9)部分。
