### ISSUE TITLE
添加已初始化容器的支持，无需再添加data

### ISSUE THREAD

**Issue by XIAOGUIGUI** [fex-team/swiper#32]
![image](https://user-images.githubusercontent.com/8243283/32695342-92314fa0-c71e-11e7-8479-389a607e20b1.png)

**Comment by zhangbobell** [comment]
目前已经支持了这一特性，文档中 Page 数据结构部分，content 可以是 String 类型，也可以是 [DOM 对象](https://github.com/fex-team/swiper#page)。DOM 对象将通过 appendChild 的方式[初始化](https://github.com/fex-team/swiper/blob/master/src/swiper.ts#L454)。
