### ISSUE TITLE
keepDefaultClasses 文档中单词写错了少写了个es

### ISSUE THREAD

**Issue by hugywin** [fex-team/swiper#36]
interface.ts 文件
export interface Options {
    container?: HTMLElement;
    data?: Page[];
    debug?: boolean;
    isVertical?: boolean;
    isLoop?: boolean;    
    initIndex?: number;
    keepDefaultClasses?: string[];
    transition?: Transition;
}

**Comment by zhangbobell** [comment]
已经修复了这个问题，感谢指正！
