### ISSUE TITLE
想问下怎么得到js滑动版本的js源代码

### ISSUE THREAD

**Issue by anota** [fex-team/swiper#38]
你好，因为现在ios11运行css3动画有时候会有坑，所以想用js版本的滑动版本，要怎么才能编译成js源代码呢，或者能否提供一份

**Comment by zhangbobell** [comment]
见 https://github.com/fex-team/swiper/releases 页面。

**Comment by anota** [comment]
这个页面只有css3版本的swiper,我要的是ref分支的js版本，请问有吗？就这个demo上的swiper
http://zhangbobell.baiduux.com/h5/car-js-animation.html

**Comment by zhangbobell** [comment]
你需要 clone  `raf` 分支，然后运行 `yarn build` 或者 `npm run build`
