### ISSUE TITLE
如何支持Page内包含滚动条的情况？

### ISSUE THREAD

**Issue by EdgarAllanzp** [fex-team/swiper#39]
某个Page是个长页面，Page内需要滚动浏览，同时不影响翻页。
例如这个[**H5**](https://ac.alloyteam.com/?stype=2&from=groupmessage) 。

**Comment by sharehua** [comment]
请教如何解决这个问题的？

**Comment by EdgarAllanzp** [comment]
@sharehua 我自己写了个轮子，检测滚动边界值
